In [ ]:
print("hello Pandas")

hello Pandas

# Pandas
Library for working with real-world data

In [ ]:
%pip install pandas

In [2]:
from numpy import int8
import pandas as pd
# Core data structure
# 1. series
s = pd.Series([10, 20, 30], dtype = int8)
print(s)

0    10
1    20
2    30
dtype: int8

In [4]:
# 2. dataframe
# 👉 DataFrame = Table (rows + columns)
data ={
    "name":["A","B","C"],
    "marks": [85, 90, 78]
}
df = pd.DataFrame(data, index=[10,20,30])
print(df)

   name  marks
10    A     85
20    B     90
30    C     78

In [ ]:
# Basic Operation
print(df.head())        # first 5 rows
print(df.tail())        # last 5 rows
print(df.shape)         # (rows, columns)
print(df.columns)       # columns name

  name  marks
0    A     85
1    B     90
2    C     78
  name  marks
0    A     85
1    B     90
2    C     78
(3, 2)
Index(['name', 'marks'], dtype='object')

In [ ]:
# Accessing Data
df["name"]                    # prints only name columns
df[["name","marks"]]          # multiple columns

# 👉 Index = row identifiers (names of rows)
# 👉 Labels = names used to identify rows or columns
# Row access
print(df.iloc[0])                   # by index
df.loc[20]                           # by label

name      A
marks    85
Name: 10, dtype: object

name      B
marks    90
Name: 20, dtype: object

In [ ]:
# Filtering data
df[df["marks"]>80]

   name  marks
10    A     85
20    B     90

In [ ]:
# Adding columns
df["grade"] = ["A", "A+", "B"]
print(df)

   name  marks grade
10    A     85     A
20    B     90    A+
30    C     78     B

In [ ]:
# basic statistics
import numpy as np

np.round(df["marks"].mean(),2)
df["marks"].max()
df["marks"].min()

78

In [ ]:
# handling missing data
df.isnull()     # checks if any valu in df is null or not
df.dropna()     # drop nulls
df.fillna(0)    # replace nulls

   name  marks grade
10    A     85     A
20    B     90    A+
30    C     78     B

In [ ]:
# reading files
# df = pd.read_csv("data.csv")

In [ ]:
# sorting data
df.sort_values(by="marks")

   name  marks grade
30    C     78     B
10    A     85     A
20    B     90    A+

In [ ]:
# Group By
data = {
    "dept": ["IT", "HR", "IT", "HR"],
    "salary": [50000, 40000, 60000, 45000]
}

df = pd.DataFrame(data)

df.groupby("dept")["salary"].mean()

dept
HR    42500.0
IT    55000.0
Name: salary, dtype: float64

In [ ]:
import pandas as pd

data = {
    "name": ["A", "B", "C", "D"],
    "marks": [85, 45, 90, 60]
}
df = pd.DataFrame(data)
df[df["marks"]>50]

df["result"]= ["pass", "fail", "pass", "pass"]
print(df)

count = 0
sum = 0
for val in df["marks"]:
  count += 1
  sum += val

print("avg is : ", sum / count)
print("avg is:", df["marks"].mean())

df["marks"].sort_values(ascending=False)

  name  marks result
0    A     85   pass
1    B     45   fail
2    C     90   pass
3    D     60   pass
avg is :  70.0
avg is: 70.0

2    90
0    85
3    60
1    45
Name: marks, dtype: int64

Intermediate Pandas

In [13]:
# Conditional Filtering 
import pandas as pd
data = {
    "name": ["tarun","arun","varun"],
    "marks": [20,50,80]
}
df = pd.DataFrame(data, index=[10,20,30])
print(df)

df[(df["marks"] > 50) & (df["marks"]<90)]

     name  marks
10  tarun     20
20   arun     50
30  varun     80

     name  marks
30  varun     80

In [ ]:
# Apply Function
# The .apply() method is a Pandas tool used to "apply" 
# a function along an axis of a DataFrame or a Series (a column).

# A lambda function is a small, anonymous function. {lambda arguments: expression}
# Unlike a standard function defined with def, a 
# lambda has no name and is contained in a single line of code.

df["marks"].apply(lambda x: x+5)

10    25
20    55
30    85
Name: marks, dtype: int64

In [16]:
df["status"] = df["marks"].apply(lambda x : 'Pass' if x >20 else 'Fail')
print(df)

     name  marks status
10  tarun     20   Fail
20   arun     50   Pass
30  varun     80   Pass

In [ ]:
def msg(marks):
    if(marks <= 20):
        return "can do better"
    elif(marks > 20 and marks <= 50):
        return "can do good"
    else:
        return "excellent"
# In standard Python, you call a function immediately: msg(20). 
# But in Pandas, you aren't calling the function; you are passing the function.
df["msg"] = df["marks"].apply(msg)
print(df)

     name  marks status            msg
10  tarun     20   Fail  can do better
20   arun     50   Pass    can do good
30  varun     80   Pass      excellent

In [30]:
# Sorting Multiple Columns

# by = [primary sort , secondary sort]
# if primary tie break then we sort on the basis of secondary sort
# ascending = [false, true] primary sort in descending and secondary in ascending order

df.sort_values(by= ["marks","name"], ascending=[False, True])

     name  marks status            msg
30  varun     80   Pass      excellent
20   arun     50   Pass    can do good
10  tarun     20   Fail  can do better

In [34]:
# Rename columns
# df.rename() used to change labels allows to change hust one specific name 
# columns = {old_col_name, new_col_name} can change multiple col name simultaneously like:
                # columns = {old1:new1, old2:new2, .....}
# inplace , if Flase(default) it only shows the preview of result original df remain unchanged
#           if True (manual) it change the df originally

df.rename(columns={"marks": "score"}, inplace = True)
print(df)

     name  score status            msg
10  tarun     20   Fail  can do better
20   arun     50   Pass    can do good
30  varun     80   Pass      excellent

In [36]:
df.loc[40] = ["kiran", 75, 'pass', "can do better"]
print(df)

     name  score status            msg
10  tarun     20   Fail  can do better
20   arun     50   Pass    can do good
30  varun     80   Pass      excellent
40  kiran     75   pass  can do better

In [ ]:
# Drop column / rows
df.drop("score", axis = 1) # column after delete it shows the preview cause no inplace is true here
df.drop(40, axis = 0) # row same here it is the preview

     name  score status            msg
10  tarun     20   Fail  can do better
20   arun     50   Pass    can do good
30  varun     80   Pass      excellent

In [45]:
# Merge (sql join)
df1 = pd.DataFrame({
    "id":[1,2],
    "name":["A","B"]
})

df2 = pd.DataFrame({
    "id":[1,2],
    "marks":[80, 90]
})

pd.merge(df1,df2, on="id")                  # Inner join
pd.merge(df1,df2, on="id", how = "left")    # left join
pd.merge(df1, df2, on="id", how="right")    # right join
pd.merge(df1, df2, on="id", how="outer")    # outer join

   id name  marks
0   1    A     80
1   2    B     90

In [48]:
# df.pivot_table() , is summary tool of pandas shonks long data into meaning full report
df.loc[40] = ["tarun", 30, 'fail', "can do better"]
df.pivot_table(values="score", index="name", aggfunc="mean")
print(df)

     name  score status            msg
10  tarun     20   Fail  can do better
20   arun     50   Pass    can do good
30  varun     80   Pass      excellent
40  tarun     30   fail  can do better

In [53]:
# Handling duplicated
df.loc[50] = ["arun", 50, 'Pass',"can do good"]
df.duplicated()

# Returns True/False for every row based ONLY on the "name" column
duplicates = df.duplicated(subset=["name"])
print(duplicates)

# To actually see the duplicate rows:
print(df[df.duplicated(subset=["name"])])

10    False
20    False
30    False
40     True
50     True
dtype: bool
     name  score status            msg
40  tarun     30   fail  can do better
50   arun     50   Pass    can do good

In [ ]:
# String operation
df["name"].str.upper()
df["name"].str.contains("A") # Case sensitive, return true or false 

# print(df)

10    False
20    False
30    False
40    False
50    False
Name: name, dtype: bool

In [74]:
import pandas as pd

data = {
    "name": ["A", "B", "C", "A"],
    "marks": [85, 40, 90, 85],
    "dept": ["IT", "HR", "IT", "IT"]
}

df = pd.DataFrame(data)

df.drop_duplicates()
df["result"] = df["marks"].apply(lambda x: 'Pass' if x > 40 else 'Fail')
print(df)

df.groupby("dept")["marks"].mean()

df.sort_values(by= ["marks"], ascending = False)
print(df["name"].str.lower())

  name  marks dept result
0    A     85   IT   Pass
1    B     40   HR   Fail
2    C     90   IT   Pass
3    A     85   IT   Pass
0    a
1    b
2    c
3    a
Name: name, dtype: object

WORKING WITH LARGE DATASET

In [75]:
df = pd.read_csv("data.csv")

In [79]:
df.info()               # show the columns -> not null count and Dtype
df.describe()           # show statistics -> mean, std, min, 25%, 50%, 75%, max
df.sample(5)            # show random 5 rows

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 3333 entries, 0 to 3332
Data columns (total 11 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   Churn            3333 non-null   int64
 1   AccountWeeks     3333 non-null   int64
 2   ContractRenewal  3333 non-null   int64
 3   DataPlan         3333 non-null   int64
 4   DataUsage        3333 non-null   float64
 5   CustServCalls    3333 non-null   int64
 6   DayMins          3333 non-null   float64
 7   DayCalls         3333 non-null   int64
 8   MonthlyCharge    3333 non-null   float64
 9   OverageFee       3333 non-null   float64
 10  RoamMins         3333 non-null   float64
dtypes: float64(5), int64(6)
memory usage: 286.6 KB

,Churn,AccountWeeks,ContractRenewal,DataPlan,DataUsage,CustServCalls,DayMins,DayCalls,MonthlyCharge,OverageFee,RoamMins
980,0,50,1,0,0.00,3,188.9,94,50.0,10.20,11.6
3179,0,110,1,0,0.34,1,192.6,102,51.4,8.95,9.4
296,0,74,1,0,0.20,2,85.7,83,38.0,12.39,10.1
448,0,75,1,0,0.34,1,117.3,114,41.4,10.06,12.2
2301,0,104,1,0,0.00,2,144.5,107,40.0,9.03,17.0

In [82]:
data = {
    "name": ["A", "B", "C", None],
    "marks": [85, None, 90, 40],
    "dept": ["IT", "HR", "IT", "HR"]
}

df = pd.DataFrame(data)

df["marks"].fillna(df["marks"].mean(), inplace = True)
print(df)
df["name"].fillna("Unknown", inplace = True)
print(df)

   name      marks dept
0     A  85.000000   IT
1     B  71.666667   HR
2     C  90.000000   IT
3  None  40.000000   HR
      name      marks dept
0        A  85.000000   IT
1        B  71.666667   HR
2        C  90.000000   IT
3  Unknown  40.000000   HR

/var/folders/9g/jh0thm8d3tb0vplt5nv8lbph0000gn/T/ipykernel_1290/4196426674.py:9: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["marks"].fillna(df["marks"].mean(), inplace = True)
/var/folders/9g/jh0thm8d3tb0vplt5nv8lbph0000gn/T/ipykernel_1290/4196426674.py:11: FutureWarning: A value is trying to be set on a copy of a DataFrame or Series through chained assignment using an inplace method.
The behavior will change in pandas 3.0. This inplace method will never work because the intermediate object on which we are setting values always behaves as a copy.

For example, when doing 'df[col].method(value, inplace=True)', try using 'df.method({col: value}, inplace=True)' or df[col] = df[col].method(value) instead, to perform the operation inplace on the original object.


  df["name"].fillna("Unknown", inplace = True)

In [84]:
print(df)

      name      marks dept
0        A  85.000000   IT
1        B  71.666667   HR
2        C  90.000000   IT
3  Unknown  40.000000   HR